name: Feature request
description: Suggest an idea for this project.
assignees: ['SpacingBat3']
labels: ['type:feat']
body:
  - type: textarea
    id: 
    attributes:
      label: Description
      description: Is your feature request related to a problem? Please describe.
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
  - type: textarea
    id:
    attributes:
      label: Suggestions
      description: Describe the solution you'd like.
      placeholder: A clear and concise description of what you want to happen.
  - type: textarea
    id:
    attributes:
      label: Alternatives
      description: Describe alternatives you've considered.
      placeholder: A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
      placeholder: |
        Additional information, screenshot, videos... Ex. This feature request
        is only related to Unix (Linux, BSD) builds.
